# Generated by Django 4.1.3 on 2022-12-04 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0003_alter_lobby_id_alter_lobby_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('race', models.CharField(choices=[('xxcha', 'Xxcha'), ('letnev', 'Letnev'), ('sol', 'Sol'), ('norr', 'Norr'), ('hacan', 'Hacan'), ('jol-nar', 'Jol Nar')], default=None, max_length=7, null=True)),
                ('color', models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('yellow', 'Yellow'), ('purple', 'Purple'), ('black', 'Black'), ('blue', 'Blue')], default=None, max_length=6, null=True)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.lobby')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
                'default_related_name': 'players',
                'unique_together': {('lobby', 'color'), ('user', 'lobby'), ('lobby', 'race')},
            },
        ),
    ]
