# Generated by Django 4.1.3 on 2022-12-10 20:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0004_player'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lobby',
            options={'default_related_name': 'lobbies', 'verbose_name': 'Lobby', 'verbose_name_plural': 'Lobbies'},
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('user', 'lobby'), ('lobby', 'color')},
        ),
        migrations.AddField(
            model_name='player',
            name='faction',
            field=models.CharField(choices=[('xxcha', 'Xxcha'), ('sol', 'Sol'), ('hacan', 'Hacan'), ('letnev', 'Letnev'), ('sardakk_norr', 'Sardakk Norr'), ('jol_nar', 'Jol Nar')], default=None, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('user', 'lobby'), ('lobby', 'color'), ('lobby', 'faction')},
        ),
        migrations.RemoveField(
            model_name='player',
            name='race',
        ),
    ]
