# Generated by Django 4.1.3 on 2022-12-20 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_lobby_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='player',
            name='users',
        ),
    ]
