# Generated by Django 4.1.3 on 2022-12-11 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_lobby_options_alter_player_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseTile',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'BaseTile',
                'verbose_name_plural': 'BaseTiles',
                'default_related_name': 'base_tiles',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'default_related_name': 'games',
            },
        ),
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q', models.SmallIntegerField()),
                ('r', models.SmallIntegerField()),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.basetile')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
            ],
            options={
                'verbose_name': 'Tile',
                'verbose_name_plural': 'Tiles',
                'default_related_name': 'tiles',
                'unique_together': {('game', 'q', 'r'), ('game', 'base')},
            },
        ),
    ]
