# Generated by Django 4.1.3 on 2022-12-31 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_player_options_alter_player_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'default_related_name': 'players', 'verbose_name': 'Player', 'verbose_name_plural': 'Players'},
        ),
    ]
