# Generated by Django 4.1.3 on 2022-12-11 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_basetile_game_tile'),
    ]

    operations = [
        migrations.AddField(
            model_name='basetile',
            name='faction',
            field=models.CharField(choices=[('xxcha', 'Xxcha'), ('sol', 'Sol'), ('hacan', 'Hacan'), ('letnev', 'Letnev'), ('sardakk_norr', 'Sardakk Norr'), ('jol_nar', 'Jol Nar')], default=None, max_length=12, null=True),
        ),
    ]
