# Generated by Django 4.1.3 on 2022-12-31 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0007_alter_player_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='users',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('lobby', 'race'), ('lobby', 'color'), ('users', 'lobby')},
        ),
    ]
