# Generated by Django 4.1.3 on 2022-12-31 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_player_user_alter_player_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='users',
            new_name='user',
        ),
    ]
