# Generated by Django 4.1.3 on 2022-12-18 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_planet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BaseTile',
            new_name='BaseSystem',
        ),
        migrations.RenameModel(
            old_name='Tile',
            new_name='System',
        ),
        migrations.AlterModelOptions(
            name='basesystem',
            options={'default_related_name': 'base_systems', 'verbose_name': 'Base System', 'verbose_name_plural': 'Base Systems'},
        ),
        migrations.AlterModelOptions(
            name='system',
            options={'default_related_name': 'systems', 'verbose_name': 'System', 'verbose_name_plural': 'Systems'},
        ),
    ]
