# Generated by Django 4.1.3 on 2022-12-18 04:05

from django.db import migrations, models
import django.utils.timezone
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_rename_basetile_basesystem_rename_tile_system_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, length=8, max_length=8, prefix='', primary_key=True, serialize=False),
        ),
    ]
