# Generated by Django 4.1.3 on 2022-12-18 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_game_created_at_game_updated_at_alter_game_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planet',
            old_name='tile',
            new_name='system',
        ),
        migrations.AlterUniqueTogether(
            name='planet',
            unique_together={('system', 'base')},
        ),
    ]
