# Generated by Django 4.1.3 on 2022-12-18 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_rename_tile_planet_system_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseplanet',
            old_name='base_tile',
            new_name='base_system',
        ),
    ]
