# Generated by Django 4.1.3 on 2023-01-02 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_alter_player_unique_together'),
        ('game', '0013_rename_base_tile_baseplanet_base_system'),
    ]

    operations = [
    ]
