# Generated by Django 4.1.4 on 2023-01-02 08:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_rename_base_tile_baseplanet_base_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(default='', max_length=30, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
