# Generated by Django 4.1.4 on 2023-01-02 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0014_game_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='player',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='player',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.game'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('user', 'game'), ('game', 'color'), ('game', 'faction')},
        ),
        migrations.RemoveField(
            model_name='player',
            name='lobby',
        ),
    ]
