# Generated by Django 4.1.3 on 2023-01-02 08:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0014_merge_20230102_0800'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('lobby', 'color'), ('lobby', 'faction'), ('user', 'lobby')},
        ),
    ]
