# Generated by Django 4.1.3 on 2023-02-08 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_delete_lobby'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='phase',
            field=models.CharField(choices=[('strategy', 'Strategy'), ('action', 'Action'), ('status', 'Status'), ('agenda', 'Agenda')], default='strategy', max_length=8),
        ),
        migrations.AddField(
            model_name='game',
            name='round',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='player',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.game'),
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Leadership'), (2, 'Diplomacy'), (3, 'Politics'), (4, 'Construction'), (5, 'Trade'), (6, 'Warfare'), (7, 'Technology'), (8, 'Imperial')])),
                ('n_trade_goods', models.PositiveSmallIntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.player')),
            ],
            options={
                'verbose_name': 'Strategy',
                'verbose_name_plural': 'Strategies',
                'default_related_name': 'strategies',
                'unique_together': {('game', 'type')},
            },
        ),
    ]
