# Generated by Django 4.1.3 on 2023-02-20 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_game_speaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='active_player',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_active_player', to='game.player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='speaker',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_speaker', to='game.player'),
        ),
    ]
