# Generated by Django 4.1.3 on 2023-03-07 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_game_active_player_alter_game_speaker'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseStrategy',
            fields=[
                ('id', models.SlugField(primary_key=True, serialize=False)),
                ('initiative', models.PositiveSmallIntegerField(default=0)),
                ('label', models.CharField(max_length=50)),
            ],
            options={
                'default_related_name': 'base_strategies',
            },
        ),
        migrations.AlterUniqueTogether(
            name='strategy',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='type',
        ),
    ]
