# Generated by Django 4.1.3 on 2023-03-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_strategy_base_alter_strategy_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='started_at',
            field=models.DateTimeField(null=True),
        ),
    ]
