# Generated by Django 4.1.3 on 2023-03-12 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_game_started_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUnit',
            fields=[
                ('id', models.SlugField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('movement', models.PositiveSmallIntegerField(default=0)),
                ('cost', models.PositiveSmallIntegerField(default=0)),
                ('combat', models.PositiveSmallIntegerField(default=0)),
                ('capacity', models.PositiveSmallIntegerField(default=0)),
                ('type', models.SlugField(choices=[('flagship', 'Flagship'), ('war_sun', 'War Sun'), ('dreadnought', 'Dreadnought'), ('carrier', 'Carrier'), ('cruiser', 'Cruiser'), ('destroyer', 'Destroyer'), ('fighter', 'Fighter'), ('infantry', 'Infantry'), ('pds', 'Pds'), ('space_dock', 'Space Dock')], max_length=11)),
                ('faction', models.SlugField(choices=[('xxcha', 'Xxcha'), ('sol', 'Sol'), ('hacan', 'Hacan'), ('letnev', 'Letnev'), ('sardakk_norr', 'Sardakk Norr'), ('jol_nar', 'Jol Nar')], default=None, max_length=12, null=True)),
            ],
            options={
                'verbose_name': 'Base Unit',
                'verbose_name_plural': 'Base Units',
                'default_related_name': 'base_units',
            },
        ),
    ]
