# Generated by Django 4.1.3 on 2023-03-13 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_baseunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_damaged', models.BooleanField(default=False)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.baseunit')),
                ('owned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player')),
                ('planet', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.planet')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.system')),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'default_related_name': 'units',
            },
        ),
    ]
