# Generated by Django 4.1.3 on 2023-03-13 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCard',
            fields=[
                ('id', models.SlugField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.SlugField(max_length=30)),
                ('type', models.CharField(choices=[('stage_1', 'Obj Stage 1'), ('stage_2', 'Obj Stage 2'), ('secret', 'Obj Secret'), ('action', 'Action'), ('agenda', 'Agenda'), ('promissory', 'Promissory')], default=None, max_length=10)),
                ('victory_points', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'BaseCard',
                'verbose_name_plural': 'BaseCards',
                'default_related_name': 'base_cards',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.basecard')),
                ('claimed_by', models.ManyToManyField(related_name='claims', to='game.player')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='game.game')),
                ('owned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_by', to='game.player')),
            ],
        ),
    ]
