# Generated by Django 4.1.3 on 2023-03-16 15:05

from django.db import migrations, models
import game.models.faction


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0025_basecard_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.SlugField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('starting_units', models.JSONField(blank=True, default=list, validators=[game.models.faction.validate_unit_types])),
            ],
            options={
                'verbose_name': 'Faction',
                'verbose_name_plural': 'Factions',
                'default_related_name': 'factions',
            },
        ),
        migrations.AlterField(
            model_name='basecard',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='baseplanet',
            name='technology',
            field=models.CharField(blank=True, choices=[('biotic', 'Biotic'), ('warfare', 'Warfare'), ('propulsion', 'Propulsion'), ('cybernetic', 'Cybernetic')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='baseplanet',
            name='trait',
            field=models.CharField(blank=True, choices=[('cultural', 'Cultural'), ('hazardous', 'Hazardous'), ('industrial', 'Industrial')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='basesystem',
            name='faction',
            field=models.CharField(blank=True, choices=[('xxcha', 'Xxcha'), ('sol', 'Sol'), ('hacan', 'Hacan'), ('letnev', 'Letnev'), ('sardakk_norr', 'Sardakk Norr'), ('jol_nar', 'Jol Nar')], default=None, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='baseunit',
            name='faction',
            field=models.SlugField(blank=True, choices=[('xxcha', 'Xxcha'), ('sol', 'Sol'), ('hacan', 'Hacan'), ('letnev', 'Letnev'), ('sardakk_norr', 'Sardakk Norr'), ('jol_nar', 'Jol Nar')], default=None, max_length=12, null=True),
        ),
    ]
