# Generated by Django 4.1.3 on 2023-03-18 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0026_faction_alter_basecard_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basesystem',
            name='faction',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.faction'),
        ),
        migrations.AlterField(
            model_name='baseunit',
            name='faction',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.faction'),
        ),
        migrations.AlterField(
            model_name='player',
            name='faction',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.faction'),
        ),
    ]
