# Generated by Django 4.1.3 on 2023-04-01 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0027_alter_basesystem_faction_alter_baseunit_faction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='activated_by',
            field=models.ManyToManyField(blank=True, related_name='activated_systems', to='game.player'),
        ),
    ]
