# Generated by Django 4.1.3 on 2023-04-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0029_baseunit_category_alter_basesystem_faction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='n_commodities',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='n_fleet_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='n_strategy_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='n_tactic_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='n_trade_goods',
            field=models.IntegerField(default=0),
        ),
    ]
