# Generated by Django 4.1.3 on 2023-04-24 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0030_player_n_commodities_player_n_fleet_tokens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='n_commodities',
            field=models.IntegerField(default=2),
        ),
    ]
