# Generated by Django 4.1.7 on 2023-05-08 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0031_faction_n_commodities'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='owned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.player'),
        ),
    ]
