# Generated by Django 4.1.3 on 2023-05-08 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0032_planet_owned_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecard',
            name='body',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='basecard',
            name='flavor',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='basecard',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='basecard',
            name='trigger',
            field=models.SlugField(blank=True, choices=[('start_of_agenda_phase', 'At the start of the agenda phase'), ('after_agenda_revealed', 'After an agenda is revealed'), ('after_speaker_vote', 'After the speaker votes on an agenda'), ('start_of_invasion', 'At the start of an invasion'), ('elected_as_agenda_outcome', 'When you are elected as the outcome of an agenda'), ('after_your_ship_is_destroyed_during_space_combat', 'After 1 of your ships is destroyed during a space combat'), ('action', 'As an Action'), ('after_they_use_sustain_damage', "After another player's ship uses Sustain Damage to cancel a hit produced by your units or abilities"), ('start_of_invasion_in_a_system_that_contains_opposing_pds', "At the start of an invasion in a system that contains 1 or more of your opponents' PDS units"), ('after_you_vote', 'After you cast votes on an outcome of an agenda'), ('start_or_end_of_combat_round', 'At the start or end of a combat round'), ('after_they_move_ships_during_tactical_action', 'After another player moves ships into a system during a tactical action'), ('start_of_first_round_of_space_combat', 'At the start of the first round of a space combat'), ('after_your_ground_forces_made_combat_rolls_during_invasion', 'After your ground forces make combat rolls during a round of ground combat'), ('after_you_activate_a_system', 'After you activate a system'), ('after_you_gain_control_of_a_planet', 'When you gain control of a planet'), ('after_they_declare_retreat_during_space_combat', 'After your opponent declares a retreat during a space combat'), ('before_you_assign_hits_during_space_cannon', "Before you assign hits produced by another player's Space Cannon roll"), ('start_of_combat_round', 'At the start of a combat round'), ('after_they_commit_ground_forces', 'After another player commits ground forces to land on a planet you control'), ('when_you_would_return_strategy_cards_during_status_phase', 'When you would return your strategy card(s) during the status phase'), ('when_they_choose_a_strategy_card_during_strategy_phase', 'When another player chooses a strategy card during the strategy phase'), ('after_they_gain_control_of_your_planet', 'After another player gains control of a planet you control'), ('after_they_play_action_card_excluding_sabotage', 'When another player plays an action card other than "Sabotage"'), ('after_you_won_space_combat', 'After you win a space combat'), ('before_you_assign_hits_to_your_ships_during_space_combat', 'Before you assign hits to your ships during a space combat'), ('start_of_strategy_phase', 'At the start of the strategy phase'), ('after_you_activate_a_system_that_contains_your_ships', 'After you activate a system that contains 1 or more of your ships'), ('when_agenda_revealed', 'When an agenda is revealed')], max_length=58, null=True),
        ),
    ]
