# Generated by Django 4.1.3 on 2023-01-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(default='test', max_length=30),
            preserve_default=False,
        ),
    ]
