version: '3'

services:
  redis:
    image: redis:5-alpine
    ports:
      - '6379:6379'
  
  web:
    build:
      context: .
    container_name: twilight-imperium-web
    volumes:
      - ./src:/app
    ports:
      - '8000:80'
